apiVersion: v1
kind: Service
metadata:
  name: brain
  labels:
    run: brain
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: brain
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: brain
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: brain
      annotations:
        pod.beta.kubernetes.io/init-containers: '[
          {
            "name": "migrate-database",
            "image": "smartbox/brain",
            "imagePullPolicy": "Always",
            "env": [
              {
                "name": "RAILS_ENV",
                "value": "production"
              }
            ],
            "command": ["bundle", "exec", "rake", "db:migrate"]
          }
        ]'
    spec:
      nodeSelector:
        type: brain
      hostNetwork: true
      containers:
        - name: brain
          image: smartbox/brain
          command: ["bundle", "exec", "rails", "server", "-p", "80", "-b", "0.0.0.0"]
          env:
            - name: RAILS_ENV
              value: production
            - name: SECRET_KEY_BASE
              valueFrom:
                secretKeyRef:
                  name: brain-secrets
                  key: secret_key_base
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: brain-secrets
                  key: mysql_root_password
          ports:
            - containerPort: 80
        - name: brain-worker
          image: smartbox/brain
          command: ["bundle", "exec", "sidekiq"]
          env:
            - name: RAILS_ENV
              value: production
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: brain-secrets
                  key: mysql_root_password
