---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: brain-ingress
spec:
  template:
    metadata:
      labels:
        app: brain-ingress
    spec:
      hostNetwork: true
      nodeSelector:
        type: brain
      containers:
        - name: brain-ingress
          image: nginx:1.13.6
          env:
            - name: NGINX_PORT
              value: "80"
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d
            - name: brain-runtime
              mountPath: /run/brain
      volumes:
        - name: nginx-config
          configMap:
            name: brain-config
            items:
              - key: nginx.ingress.conf
                path: nginx.conf
        - name: brain-runtime
          hostPath:
            path: /run/brain
---
apiVersion: v1
kind: Service
metadata:
  name: brain
  labels:
    run: brain
spec:
  type: ClusterIP
  ports:
    - port: 8000
  selector:
    app: brain-internal
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: brain-internal
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: brain-internal
    spec:
      nodeSelector:
        type: brain
      containers:
        - name: brain-internal
          image: nginx:1.13.6
          env:
            - name: NGINX_PORT
              value: "8000"
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d
            - name: brain-runtime
              mountPath: /run/brain
      volumes:
        - name: nginx-config
          configMap:
            name: brain-config
            items:
              - key: nginx.internal.conf
                path: nginx.conf
        - name: brain-runtime
          hostPath:
            path: /run/brain
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: brain
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: brain
    spec:
      nodeSelector:
        type: brain
      initContainers:
        - name: create-database
          image: smartbox/brain
          imagePullPolicy: Always
          env:
            - name: RAILS_ENV
              valueFrom:
                configMapKeyRef:
                  name: brain-config
                  key: rails.env
          command: ["rake", "db:create"]
        - name: load-schema
          image: smartbox/brain
          imagePullPolicy: Always
          env:
            - name: RAILS_ENV
              valueFrom:
                configMapKeyRef:
                  name: brain-config
                  key: rails.env
          command: ["rake", "db:schema:load"]
        - name: migrate-database
          image: smartbox/brain
          imagePullPolicy: Always
          env:
            - name: RAILS_ENV
              valueFrom:
                configMapKeyRef:
                  name: brain-config
                  key: rails.env
          command: ["rake", "db:migrate"]
      containers:
        - name: brain
          image: smartbox/brain
          command: ["puma", "-C", "/brain/config/puma.rb"]
          env:
            - name: RAILS_ENV
              valueFrom:
                configMapKeyRef:
                  name: brain-config
                  key: rails.env
            - name: SECRET_KEY_BASE
              valueFrom:
                secretKeyRef:
                  name: brain-secrets
                  key: secret_key_base
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: brain-secrets
                  key: mysql_root_password
          volumeMounts:
            - mountPath: /run/brain
              name: brain-runtime
        - name: brain-worker
          image: smartbox/brain
          command: ["sidekiq"]
          env:
            - name: RAILS_ENV
              valueFrom:
                configMapKeyRef:
                  name: brain-config
                  key: rails.env
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: brain-secrets
                  key: mysql_root_password
      volumes:
        - name: brain-runtime
          hostPath:
            path: /run/brain
