apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: cell
spec:
  selector:
      matchLabels:
        name: cell
  template:
    metadata:
      labels:
        name: cell
    spec:
      nodeSelector:
        type: cell
      containers:
        - name: cell
          image: smartbox/cell
          command: ["bundle", "exec", "rails", "server", "-p", "80", "-b", "0.0.0.0"]
          env:
            - name: RAILS_ENV
              value: production
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /volumes
              name: volumes
          volumeMounts:
            - mountPath: /etc/brain
              name: brain-config
      volumes:
        - name: volumes
          hostPath:
            path: /volumes
        - name: brain-config
          hostPath:
            path: /etc/brain
