---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: cell-ingress
spec:
  template:
    metadata:
      labels:
        app: cell-ingress
    spec:
      hostNetwork: true
      nodeSelector:
        type: cell
      containers:
        - name: cell-ingress
          image: nginx
          env:
            - name: NGINX_PORT
              value: "80"
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d
            - name: cell-runtime
              mountPath: /run/cell
      volumes:
        - name: nginx-config
          configMap:
            name: cell-config
            items:
              - key: nginx.ingress.conf
                path: nginx.conf
        - name: cell-runtime
          hostPath:
            path: /run/cell
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: cell
spec:
  selector:
    matchLabels:
      app: cell
  template:
    metadata:
      labels:
        app: cell
    spec:
      nodeSelector:
        type: cell
      containers:
        - name: cell
          image: smartbox/cell
          command: ["puma", "-C", "/cell/config/puma.rb"]
          env:
            - name: RAILS_ENV
              valueFrom:
                configMapKeyRef:
                  name: cell-config
                  key: rails.env
            - name: SECRET_KEY_BASE
              valueFrom:
                secretKeyRef:
                  name: cell-secrets
                  key: secret_key_base
            - name: HOST_IP_ADDRESS
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - mountPath: /volumes
              name: volumes
            - mountPath: /etc/cell
              name: cell-config
            - mountPath: /run/cell
              name: cell-runtime
      volumes:
        - name: volumes
          hostPath:
            path: /volumes
        - name: cell-config
          hostPath:
            path: /etc/cell
        - name: cell-runtime
          hostPath:
            path: /run/cell
