---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  labels:
    run: mongodb
spec:
  ports:
    - port: 27017
  selector:
    app: mongodb
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mongodb
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      nodeSelector:
        type: brain
      containers:
        - name: mongodb
          image: mongo:3.4.10
          volumeMounts:
            - mountPath: /var/lib/mongodb
              name: mongodb-data
      volumes:
        - name: mongodb-data
          hostPath:
            path: /var/lib/mongodb
