---
apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    run: redis
spec:
  ports:
    - port: 6379
  selector:
    app: redis
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
    spec:
      nodeSelector:
        type: brain
      containers:
        - name: redis
          image: redis
          volumeMounts:
            - mountPath: /var/lib/redis
              name: redis-data
      volumes:
        - name: redis-data
          hostPath:
            path: /var/lib/redis
